//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAceess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceLog
    {
        public long ID { get; set; }
        public int DeviceID { get; set; }
        public int EmployeID { get; set; }
        public System.DateTime LogTime { get; set; }
        public string LogType { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual FingerPrintDevice FingerPrintDevice { get; set; }
    }
}
