//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAceess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerPrintDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FingerPrintDevice()
        {
            this.AttendanceLogs = new HashSet<AttendanceLog>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string LocationDesc { get; set; }
        public string IP { get; set; }
        public Nullable<long> Port { get; set; }
        public string Mac { get; set; }
        public string Model { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Vendor { get; set; }
        public string SerialNumber { get; set; }
        public string FirmwareVer { get; set; }
        public string Platform { get; set; }
        public Nullable<System.DateTime> ProductionTime { get; set; }
        public Nullable<System.DateTime> LatestLogTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
